### ISSUE TITLE
`yew::Component` is not implemented for `yew::functional::FunctionComponent<bounce::provider::bounce_root>` for yew 0.20

### ISSUE THREAD

**Issue by DenuxPlays** [bounce-rs/bounce#46]
![image](https://user-images.githubusercontent.com/83671398/202478603-e8bd3b27-4689-4cd6-9a27-3a6f16034e72.png)

Same issues with:
`HelmetBridge`
`Helmet`

**Comment by futursolo** [comment]
This is likely due to you are using an incompatible version of bounce with Yew. Bounce v0.3.0 is only compatible with Yew v0.19.

I have just released Bounce v0.4.0 with Yew v0.20 support.
Could you please try with upgrading to Bounce v0.4.0 with the non-git version of Yew (version = "0.20.0")?

**Comment by DenuxPlays** [comment]
> This is likely due to you are using an incompatible version of bounce with Yew. Bounce v0.3.0 is only compatible with Yew v0.19.
> 
> I have just released Bounce v0.4.0 with Yew v0.20 support. Could you please try with upgrading to Bounce v0.4.0 with the non-git version of Yew (version = "0.20.0")?

Yeah worked with yew 0.20 and bounce 0.4.0
Thank you
