### ISSUE TITLE
Helmet support for meta tags incorrectly merges OpenGraph meta tags

### ISSUE THREAD

**Issue by kinnison** [bounce-rs/bounce#62]
The Open Graph protocol (https://ogp.me) specifies the use of `<meta>` tags to provide graph data (it's how Facebook does fancy page metadata for links).

The distinguishing attribute for these is `property` but deduplication of meta tags in the helmet feature does not use that attribute when keying the tags during merge.

Please could you add `property` to the set of attributes used for meta tag deduplication?

**Comment by futursolo** [comment]
I think the current deduplication logic is overly complicated.

I intend to switch to the logic used by `next/head` where the `key` attribute is used to deduplicate tags.

**Comment by kinnison** [comment]
Is there anything I can do to help with this, or should I leave you to it?

**Comment by futursolo** [comment]
It may still take some time before I can get to this.

If you want to submit a pull request to fix this in the meanwhile, I am more than happy to review it.

**Comment by kinnison** [comment]
I've submitted a PR which adds the relevant attribute to the existing deduplicator since I'm not very good at understanding next-js.  I realise it's not ideal, but it does solve my use-case for now.  if you're not OK to merge/release with that tweak then I understand, I can continue to use my fork for now.
