### ISSUE TITLE
"Error: no bounce root found" when using `use_atom`

### ISSUE THREAD

**Issue by sam0x17** [bounce-rs/bounce#65]
when I try to use bounce as follows with a simple `use_atom` I get the error "Error: No bounce root found". I get this error as long as I have a `use_atom` line in my `app()` function, even if I don't use it in the markup.

```rust
use bounce::*;
use yew::prelude::*;

#[derive(PartialEq, Clone, Eq, Atom)]
struct SimpleAtom {
    something: bool,
}

impl Default for SimpleAtom {
    fn default() -> Self {
        Self { something: false }
    }
}

#[function_component(App)]
fn app() -> Html {
    let simple = use_atom::<SimpleAtom>();
    html! {
        <BounceRoot>
            <h1>{"hello"}</h1>
            if simple.something {
                <h1>{"more stuff"}</h1>
            }
        </BounceRoot>
    }
}

fn main() {
    yew::Renderer::<App>::new().render();
}

```

**Comment by sam0x17** [comment]
Never mind, I had a bad atom that was causing this

**Comment by sam0x17** [comment]
It seems to happen if there are any usages of `use_atom`

**Comment by futursolo** [comment]
BounceRoot is a context provider, which means normal rules of context provider apply.
Hooks that rely on bounce root must have a bounce root present in its ancestors (not the current one).

```rust
#[function_component(App)]
fn app() -> Html {
    // Looking for bounce root in ancestors of App, which cannot be found.
    let simple = use_atom::<SimpleAtom>();
    html! {
        <BounceRoot>
            <h1>{"hello"}</h1>
            if simple.something {
                <h1>{"more stuff"}</h1>
            }
        </BounceRoot>
    }
}
```

```rust
#[function_component]
fn Content() -> Html {
    // Looking for bounce root in ancestors of Content, which can be found in App.
    let simple = use_atom::<SimpleAtom>();

    return html! {
        <h1>{"hello"}</h1>
        if simple.something {
            <h1>{"more stuff"}</h1>
        }
    }
}


#[function_component(App)]
fn app() -> Html {
    // Looking for bounce root in parents of app, which cannot be found.
    let simple = use_atom::<SimpleAtom>();
    html! {
        <BounceRoot>
            <Content />
        </BounceRoot>
    }
}
```

**Comment by sam0x17** [comment]
so I'm not allowed to do anything dynamic in the main `App` one basically, it has to be in child components?

**Comment by sam0x17** [comment]
Also in your example there are multiple `BounceRoot` tags.. does this mean I need one for every component?

**Comment by futursolo** [comment]
No, you can only have 1 bounce root per application.

You cannot use bounce hooks in the component it presents, only its children.
This means that you will not be able to use it in an existing top most component.
There is nothing special with the top most component.
You can simply add a parent that does nothing but registers a bounce root.

You may find [this example](https://github.com/bounce-rs/bounce/blob/master/examples/helmet-title/src/main.rs#L79) helpful.
